version: 2
registries:
  maven-repository-maven-pkg-github-com-navikt-fp-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles/
    username: x-access-token
    password: "${{secrets.MAVEN_REPOSITORY_MAVEN_PKG_GITHUB_COM_NAVIKT_FP_FELLES_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.nimbusds:nimbus-jose-jwt
    versions:
    - 9.4.2
    - "9.5"
    - "9.6"
    - "9.7"
    - "9.8"
    - 9.8.1
  - dependency-name: com.nimbusds:oauth2-oidc-sdk
    versions:
    - "9.0"
    - "9.1"
    - "9.2"
    - 9.3.1
  - dependency-name: no.nav.security:mock-oauth2-server
    versions:
    - 0.3.1
  - dependency-name: com.github.ben-manes.caffeine:caffeine
    versions:
    - 2.9.0
  registries:
  - maven-repository-maven-pkg-github-com-navikt-fp-felles
